name = "qwind-project"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true
route = ""
zone_id = ""

[env.production]
bucket = "./dist"
entry_point = "./src/entry.ssr.tsx"

[build]
  command = "npm run build"
  directory = "./dist"

[deploy]
  dir = "./dist"