name name = "qwind-project"
type = "javascript"

account_id = "75303e95c0cb01d345d388ddf6c7284b"
workers_dev = true
route = ""
zone_id = ""

[build]
  command = "npm run build"  # Ensure the build command is correct
  directory = "dist"  # This is the output directory where your built files will be

[env.production]
  pages_build_output_dir = "dist"  # This is where Cloudflare Pages looks for your build output
